version: '3.8'

services:
  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
      - wiam-network

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
      - wiam-network

<<<<<<< HEAD
  pgsql:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=yii2advanced
      - POSTGRES_USER=yii2advanced
      - POSTGRES_PASSWORD=secret
    networks:
      - wiam-network

=======
  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=verysecret
  #     - MYSQL_DATABASE=yii2advanced
  #     - MYSQL_USER=yii2advanced
  #     - MYSQL_PASSWORD=secret

  pgsql:
   image: postgres:9.5
   environment:
     - POSTGRES_DB=yii2advanced
     - POSTGRES_USER=yii2advanced
     - POSTGRES_PASSWORD=secret
>>>>>>> 7f8152e5f2d7123a2eb440647058be7def760ceb
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@webandtravel.com
<<<<<<< HEAD
      PGADMIN_DEFAULT_PASSWORD: admin@webandtravel.com
    ports:
      - 5050:80
    networks:
      - wiam-network

networks:
  wiam-network:
    driver: bridge
=======
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - pgsql
>>>>>>> 7f8152e5f2d7123a2eb440647058be7def760ceb
